# Generated by Django 5.1.2 on 2024-10-31 04:14

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=media.models.upload_to_unique),
        ),
    ]
