# Generated by Django 5.1.2 on 2024-10-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
